### ISSUE TITLE
Theme hides scrollbars with no option to return them

### ISSUE THREAD

**Issue by Psypher1** [rivea0/obsidian-prime#5] opened 2024-06-11 17:58 UTC
I am not sure if this is a setting, but the scrollbars seem to be hidden. Could we get them back or an option to toggle them. I don't see one in style settings .... 

I am including 2 pictures as reference

## Default Theme
![default](https://github.com/rivea0/obsidian-prime/assets/34038162/de0ec179-5e8b-4235-8795-f17c63351a2c)

## Prime Theme

![prime](https://github.com/rivea0/obsidian-prime/assets/34038162/3c682b8c-acd9-4f15-bedd-ea6d0a5278d1)

**Comment by rivea0** [comment] 2024-06-12 09:02
Hey @Psypher1, can you share the operating system you're using? Obsidian keeps the native scrollbars for macOS (check out this comment: https://forum.obsidian.md/t/allow-native-scroll-bars/23468/4), so they stay hidden—when you're not scrolling—in other themes as well, including the default theme, as far as I've observed. But other operating systems were not mentioned, so I'm not sure if the problem is related to that.

In the meantime, I added an option in the new update (v1.1.1) to use "styled scrollbars" under the Tweaks section in Style Settings, which replaces the native scrollbars, so they will always be shown. Let me know if it helps.

**Comment by Psypher1** [comment] 2024-06-12 17:18
I'm on Windows 10 @rivea0 


And yes! The update you made has helped... Didn't even need to adjust style settings

**Comment by rivea0** [comment] 2024-06-13 07:45
OK, so it's probably related to the native scrollbars, although I'm not perfectly sure why that problem happens.

I'm glad it helped, though! Closing this issue for now, thanks for your feedback and help with improving this theme.

**Closed as completed by rivea0** 2024-06-13 07:45 UTC
